repos:
- hooks:
  - id: end-of-file-fixer
  - id: trailing-whitespace
  - id: check-added-large-files
  - id: check-ast
  - id: check-merge-conflict
  - id: check-toml
  - id: check-yaml
  - id: file-contents-sorter
    files: .gitignore
    args: [--unique]
  - id: fix-encoding-pragma
  repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
- hooks:
  - id: commitizen
  repo: https://github.com/commitizen-tools/commitizen
  rev: v2.42.1
- hooks:
    - id: fmt
    - id: cargo-check
  repo: https://github.com/doublify/pre-commit-rust
  rev: v1.0
